# utils.py - Utility functions for OpenDeepResearcher

import re
import time
from typing import List, Dict, Any
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from io import BytesIO

def clean_text(text: str) -> str:
    """Clean and normalize text content"""
    if not text:
        return ""
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text.strip())
    
    # Remove special characters that might cause issues
    text = re.sub(r'[^\w\s\-.,!?;:()\[\]{}"]', '', text)
    
    return text

def truncate_content(content: str, max_length: int = 350) -> str:
    """Truncate content to specified length"""
    if not content or len(content) <= max_length:
        return content
    
    # Try to truncate at sentence boundary
    truncated = content[:max_length]
    last_period = truncated.rfind('.')
    last_space = truncated.rfind(' ')
    
    if last_period > max_length * 0.8:
        return content[:last_period + 1]
    elif last_space > max_length * 0.8:
        return content[:last_space] + "..."
    else:
        return content[:max_length] + "..."

def format_timestamp() -> str:
    """Get formatted timestamp for logging"""
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def sanitize_filename(filename: str) -> str:
    """Sanitize filename for safe file operations"""
    # Remove invalid characters
    filename = re.sub(r'[<>:"/\\|?*]', '_', filename)
    
    # Limit length
    if len(filename) > 100:
        filename = filename[:100]
    
    return filename.strip()

def validate_topic(topic: str) -> bool:
    """Validate research topic input"""
    if not topic or not topic.strip():
        return False
    
    # Check minimum length
    if len(topic.strip()) < 5:
        return False
    
    # Check maximum length
    if len(topic.strip()) > 500:
        return False
    
    return True

def extract_questions_from_text(text: str) -> List[str]:
    """Extract numbered questions from text"""
    questions = []
    lines = text.strip().split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Match numbered list items (1. 2. etc.)
        match = re.match(r'^\d+\.\s*(.+)$', line)
        if match:
            question = match.group(1).strip()
            if question:
                questions.append(question)
    
    return questions

def calculate_research_stats(search_results: Dict[str, List[Dict]]) -> Dict[str, Any]:
    """Calculate statistics about research results"""
    total_sources = sum(len(results) for results in search_results.values())
    total_questions = len(search_results)
    
    # Calculate average content length
    content_lengths = []
    for results in search_results.values():
        for result in results:
            content = result.get('content', '')
            if content:
                content_lengths.append(len(content))
    
    avg_content_length = sum(content_lengths) / len(content_lengths) if content_lengths else 0
    
    return {
        'total_questions': total_questions,
        'total_sources': total_sources,
        'avg_sources_per_question': total_sources / total_questions if total_questions > 0 else 0,
        'avg_content_length': round(avg_content_length, 2)
    }

def retry_with_backoff(func, max_retries: int = 3, base_delay: float = 1.0):
    """Retry function with exponential backoff"""
    for attempt in range(max_retries):
        try:
            return func()
        except Exception as e:
            if attempt == max_retries - 1:
                raise e
            
            delay = base_delay * (2 ** attempt)
            print(f"Attempt {attempt + 1} failed, retrying in {delay}s...")
            time.sleep(delay)

def format_research_report(topic: str, sub_questions: List[str], final_report: str) -> str:
    """Format complete research report with metadata"""
    timestamp = format_timestamp()
    
    report = f"""# Research Report: {topic}

**Generated on:** {timestamp}
**Sub-questions analyzed:** {len(sub_questions)}

## Research Questions Explored

"""
    
    for i, question in enumerate(sub_questions, 1):
        report += f"{i}. {question}\n"
    
    report += f"\n## Research Findings\n\n{final_report}\n"
    
    report += f"""
---
*Report generated by OpenDeepResearcher*
*Timestamp: {timestamp}*
"""
    
    return report

def generate_pdf_report(topic: str, final_report: str, sources: List[Dict], sub_questions: List[str]) -> bytes:
    """Generate PDF report with references"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=1*inch, title=topic)
    
    # Get styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=HexColor('#2c5aa0'),
        spaceAfter=30,
        alignment=1  # Center alignment
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=HexColor('#2c5aa0'),
        spaceBefore=20,
        spaceAfter=10
    )
    
    # Build content
    content = []
    
    # Title
    content.append(Paragraph(f"Research Report: {topic}", title_style))
    content.append(Spacer(1, 20))
    
    # Metadata
    timestamp = format_timestamp()
    content.append(Paragraph(f"<b>Generated on:</b> {timestamp}", styles['Normal']))
    content.append(Paragraph(f"<b>Sub-questions analyzed:</b> {len(sub_questions)}", styles['Normal']))
    content.append(Spacer(1, 20))
    
    # Research Questions
    content.append(Paragraph("Research Questions Explored", heading_style))
    for i, question in enumerate(sub_questions, 1):
        content.append(Paragraph(f"{i}. {question}", styles['Normal']))
    content.append(Spacer(1, 20))
    
    # Research Findings
    content.append(Paragraph("Research Findings", heading_style))
    
    # Split report into paragraphs and add them
    report_paragraphs = final_report.split('\n\n')
    for para in report_paragraphs:
        if para.strip():
            content.append(Paragraph(para.strip(), styles['Normal']))
            content.append(Spacer(1, 10))
    
    # References
    if sources:
        content.append(Spacer(1, 30))
        content.append(Paragraph("References", heading_style))
        
        # Remove duplicates while preserving order
        seen_urls = set()
        unique_sources = []
        for source in sources:
            if source['url'] not in seen_urls:
                unique_sources.append(source)
                seen_urls.add(source['url'])
        
        for i, source in enumerate(unique_sources, 1):
            ref_text = f"{i}. {source['title']} - <link href='{source['url']}'>{source['url']}</link>"
            content.append(Paragraph(ref_text, styles['Normal']))
    
    # Footer
    content.append(Spacer(1, 30))
    content.append(Paragraph("---", styles['Normal']))
    content.append(Paragraph(f"Report generated by OpenDeepResearcher on {timestamp}", styles['Italic']))
    
    # Build PDF
    doc.build(content)
    buffer.seek(0)
    return buffer.getvalue()
